version: "3.3"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=christian.szeman@gmail.com
      - OPENVPN_PASSWORD=nNDc4Qs?
      - SERVER_REGIONS=Slovakia
    networks:
      - mynetwork
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: "unless-stopped"

  futbal_dnes:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    network_mode: service:vpn
    privileged: true
    command: /bin/bash -c "python3 futbal_new.py 0"
    restart: always
    #command: /bin/bash -c "tail -f /dev/null"
    shm_size: '512mb'
  # security_opt:
    # - seccomp=$PWD/file.json

  futbal_zajtra:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    network_mode: service:vpn
    privileged: true
    command: /bin/bash -c "python3 futbal_new.py 1"
    restart: always
    #command: /bin/bash -c "tail -f /dev/null"
    shm_size: '512mb'
  # security_opt:
    # - seccomp=$PWD/file.json

networks:
  mynetwork:                                 
    external: true