version: '3.8'

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: flashscore_vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=Slovakia
    volumes:
      - ./gluetun:/gluetun
    ports:
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
    restart: unless-stopped

  flashscore-basketball:
    build: .
    container_name: flashscore_basketball
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "basketball", "--interval", "30"]
    restart: unless-stopped

  flashscore-football:
    build: .
    container_name: flashscore_football
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "football", "--interval", "30"]
    restart: unless-stopped

  flashscore-tennis:
    build: .
    container_name: flashscore_tennis
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "tennis", "--interval", "30"]
    restart: unless-stopped

  flashscore-volleyball:
    build: .
    container_name: flashscore_volleyball
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "volleyball", "--interval", "30"]
    restart: unless-stopped

  flashscore-hockey:
    build: .
    container_name: flashscore_hockey
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "hockey", "--interval", "30"]
    restart: unless-stopped

  flashscore-handball:
    build: .
    container_name: flashscore_handball
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "handball", "--interval", "30"]
    restart: unless-stopped

  flashscore-multi:
    build: .
    container_name: flashscore_multi_sport
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "src/main.py", "--monitor", "basketball", "football", "tennis", "volleyball", "hockey", "handball", "--interval", "15"]
    restart: unless-stopped
    profiles:
      - multi-sport

volumes:
  gluetun:
