version: "3.3"
services:

  # jednotka:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 tenis.py 0"
  #   restart: always
  #   #command: /bin/bash -c "tail -f /dev/null"
  #   shm_size: '512mb'
  #   # security_opt:
  #     # - seccomp=$PWD/file.json
  # dvojka:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 tenis.py 1"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # trojka:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 tenis.py 2"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # jednotka_bas:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 basketbal.py 0"
  #   restart: always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # dvojka_bas:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 basketbal.py 1"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # trojka_bas:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 basketbal.py 2"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # hadzana_dnes:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 hadzana.py 0"
  #   restart: always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # hadzana_zajtra:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 hadzana.py 1"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # hadzana_pozajtra:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 hadzana.py 2"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"


  # volejbal_dnes:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 volejbal.py 0"
  #   restart: always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  # volejbal_zajtra:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   #command: /bin/bash -c "python3 volejbal.py 1"
  #   restart : always
  #   shm_size: '512mb'
  #   command: /bin/bash -c "tail -f /dev/null"

  # volejbal_pozajtra:
  #   build: .
  #   volumes:
  #     - $PWD:/app
  #   working_dir: /app
  #   privileged: true
  #   command: /bin/bash -c "python3 volejbal.py 2"
  #   restart : always
  #   shm_size: '512mb'
  #   #command: /bin/bash -c "tail -f /dev/null"

  futbal_dnes:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 futbal.py 0"
    restart: always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

  futbal_zajtra:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 futbal.py 1"
    restart : always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

  futbal_pozajtra:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 futbal.py 2"
    restart : always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

  hokej_dnes:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 hokej.py 0"
    restart: always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

  hokej_zajtra:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 hokej.py 1"
    restart : always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

  hokej_pozajtra:
    build: .
    volumes:
      - $PWD:/app
    working_dir: /app
    privileged: true
    command: /bin/bash -c "python3 hokej.py 2"
    restart : always
    shm_size: '512mb'
    #command: /bin/bash -c "tail -f /dev/null"

